name: Build + Deploy UI to Core

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm i
          npm run build

      - name: Deploy to Target Repository
        env:
          TARGET_REPO: "OpenNanos-Community/onc-core"
          TARGET_BRANCH: "certurix/ui"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git clone --depth 1 https://x-access-token:${GITHUB_TOKEN}@github.com/$TARGET_REPO target-repo
          cd target-repo

          rm -rf ./*
          cp -r ../dist/* ./

          git add .
          git commit -m "CI: Deploy UI to Core"
          git push origin $TARGET_BRANCH
