name: Build and Deploy UI to Core

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Source Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm ci
          npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout Target Repository
        uses: actions/checkout@v3
        with:
          repository: OpenNanos-Community/onc-core
          token: ${{ secrets.GITHUB_TOKEN }}
          path: target-repo
          fetch-depth: 0  # Récupère l'historique pour manipuler la branche

      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./dist

      - name: Deploy to Target Repository
        env:
          TARGET_BRANCH: "certurix/ui"
        run: |
          cd target-repo

          # Vérifier si la branche existe, sinon la créer
          if git rev-parse --verify origin/$TARGET_BRANCH >/dev/null 2>&1; then
            git checkout $TARGET_BRANCH
          else
            git checkout -b $TARGET_BRANCH
          fi

          # Créer le dossier cible s'il n'existe pas
          mkdir -p Client/UI

          # Supprimer uniquement les fichiers existants dans Client/UI
          rm -rf Client/UI/*

          # Copier le nouveau build dans Client/UI
          cp -r ../dist/* Client/UI/

          # Vérifier s'il y a des changements avant de commit
          if git diff --staged --quiet; then
            echo "Aucune modification à commit, fin du job."
            exit 0
          fi

          git add Client/UI/*
          git commit -m "CI: Deploy UI build to Client/UI"
          git push origin $TARGET_BRANCH
